

const Footer = () => {
return(
    <>
    <div className="footer">
        <div className="footer-content">
          <div className="footer-section">
            <ul className="footer-links">
              <li>
                <a href="/terms" target='_blank' rel='noopener noreferrer' className="footer-link">
                  Terms of Service
                </a>
              </li>
            </ul>
          </div>

          <div className="footer-section">
            <ul className="footer-links">
              <li>
                <a href="/credits" target='_blank' rel='noopener noreferrer' className="footer-link">
                  Credits
                </a>
              </li>
            </ul>
          </div>

          <div className="footer-section">
            <ul className="footer-links">
              <li>
                <a href="/privacy" target='_blank' rel='noopener noreferrer' className="footer-link">
                  Privacy
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div className="footer-bottom">
          <p className="footer-copyright">© 2024 Guess Who</p>
          <p className="footer-tagline">The site owner is not liable for any content generated by users, including drawings, messages, or usernames.</p>
        </div>
      </div>
    </>
);
}

export default Footer;